### ISSUE TITLE
Move to JuliaIO

### ISSUE THREAD

**Issue by mkitti** [waralex/Blosc2.jl#6]
Hi, would you be interested in moving this package into the [JuliaIO ](https://github.com/JuliaIO)Github organization so that more people can help maintain the code?

**Comment by waralex** [comment]
Hi! I will do it with great pleasure! Unfortunately, I have very little time now and I am ashamed that the package is not developing...

**Comment by mkitti** [comment]
OK. I will have someone from JuliaIO send you an invitation to join the JuliaIO Github organization.

You will then have to follow these instructions to transfer the repository:
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by mkitti** [comment]
You should have received an invitation from @bjarthur to join the JuliaIO organization.

**Comment by mkitti** [comment]
Let me know if you did not get the JuliaIO invite.

**Comment by waralex** [comment]
>You will then have to follow these instructions to transfer the repository:

It's done

**Comment by mkitti** [comment]
Welcome to JuliaIO.
